### PR TITLE
Added support for 1.18

### PR DESCRIPTION
**Pull request by KevinDaGame**
❗❗❗❗❗❗❗ Please read the bottom comment ❗❗❗❗❗❗❗ 
This pull request adds compatibility for 1.18's new world height. It should work fine for 1.17 and lower, though untested as of now.

**Update:** Added support for custom world height and the new max height level

This pull request includes changes made by Lennard99.
[VoxelSniper-6.1.3.zip](https://github.com/ervinnnc/VoxelSniper/files/8101987/VoxelSniper-6.1.3.zip)
**WARNING:**
This is an updated version that might solve a lot of issues regarding to world height. I was not able to test all brushes though so I would appreciate it someone could test the brushes and see if they work correctly at different heights
[VoxelSniper-6.1.4.zip](https://github.com/ervinchai/VoxelSniper/files/8363688/VoxelSniper-6.1.4.zip)

### CODE REVIEW

**Comment by good3n** [comment]
While this doesn't error, this doesn't do anything below Y0 - and possibly above Y255

**Comment by KevinDaGame** [comment]
> While this doesn't error, this doesn't do anything below Y0 - and possibly above Y255

What excactly do you mean with "this doesn't do anything below y0"? From my tests brushes work until y-64.
I forgot that the new height limit is 319, so I will add that right now

**Comment by good3n** [comment]
I couldn't use a brush on anything below 0

For context I was using overlay.

**Comment by Blitheness** [comment]
Hi @KevinDaGame 

It looks like the bug @good3n is describing is in OverlayBrush.java on Line 42, where the minimum y-axis value is hard-coded to zero. Same on Line 71 in the same file.

https://github.com/KevinDaGame/VoxelSniper/blob/master/src/main/java/com/thevoxelbox/voxelsniper/brush/OverlayBrush.java#L42

**Comment by KevinDaGame** [comment]
> Hi @KevinDaGame 
> 
> It looks like the bug @good3n is describing is in OverlayBrush.java on Line 42, where the minimum y-axis value is hard-coded to zero.
> 
> https://github.com/KevinDaGame/VoxelSniper/blob/master/src/main/java/com/thevoxelbox/voxelsniper/brush/OverlayBrush.java#L42

I'll take a look at it tomorrow. If it's hard coded there, I bet it is in other places too

**Comment by IshKaigen** [comment]
> > Hi @KevinDaGame
> > It looks like the bug @good3n is describing is in OverlayBrush.java on Line 42, where the minimum y-axis value is hard-coded to zero.
> > https://github.com/KevinDaGame/VoxelSniper/blob/master/src/main/java/com/thevoxelbox/voxelsniper/brush/OverlayBrush.java#L42
> 
> I'll take a look at it tomorrow. If it's hard coded there, I bet it is in other places too

Any updates on this? Having issues using this on a flatworld due to Height.

**Comment by ZEROOblivious** [comment]
Dude my server/builders are so grateful for this fork/update.
Keep up the  good work!

**Comment by KevinDaGame** [comment]
> > > Hi @KevinDaGame
> > > It looks like the bug @good3n is describing is in OverlayBrush.java on Line 42, where the minimum y-axis value is hard-coded to zero.
> > > https://github.com/KevinDaGame/VoxelSniper/blob/master/src/main/java/com/thevoxelbox/voxelsniper/brush/OverlayBrush.java#L42
> > 
> > 
> > I'll take a look at it tomorrow. If it's hard coded there, I bet it is in other places too
> 
> Any updates on this? Having issues using this on a flatworld due to Height.

Sorry! I fixed it but never put it on github. I will do so now!

**Comment by KevinDaGame** [comment]
@IshKaigen @ZEROOblivious  @good3n @Blitheness Check the main comment for an update. I'd appreciate it if someone could do some testing.

**Comment by KevinDaGame** [comment]
> Dude my server/builders are so grateful for this fork/update. Keep up the good work!

Glad it helps. That brings the count up to two grateful servers 😄

**Comment by jakearenberg8** [comment]
Hey man, just reactivated my account to let you know you are awesome. I've been using voxel sniper since the beta days, can't thank you enough for this update. Cheers!

**Comment by KevinDaGame** [comment]
> Hey man, just reactivated my account to let you know you are awesome. I've been using voxel sniper since the beta days, can't thank you enough for this update. Cheers!

No problem! While I no longer use it myself, I used to use it a lot, and I know how useful it is. I really appreciate it

**Comment by Tugdual19** [comment]
Hi how am i suppose to add all of this update? I'm new on github so I don't konw. Does i just need to download 6.1.4 or is there something else to do? sorry for my english i'm french

**Comment by YouSureDude** [comment]
Hello it seems like the /b blenddisc does not work!

**Comment by ZEROOblivious** [comment]
I'd love to test, its just I don't really understand the coding side of this stuff sadly. If you send me a Test Jar file we can test what you're questioning? My team will be willing to do it.

**Comment by KevinDaGame** [comment]
> Hi how am i suppose to add all of this update? I'm new on github so I don't konw. Does i just need to download 6.1.4 or is there something else to do? sorry for my english i'm french

Sorry for the late response, yes 6.1.4 is the latest (experimental) version. If you want to play it safe, then there is 6.1.3 which has some confirmed issues

**Comment by KevinDaGame** [comment]
@ZEROOblivious @YouSureDude I'm probably going to expand this project next week since I have the time and people seem to want it. I will fix the known issues and probably also make a checklist for testing the brushes

**Comment by M3TTA** [comment]
salute for keeping this updated

**Comment by Lennart99** [comment]
Hi, just saw this, I also opened a PR for this, but unfortunately the original author seems really inactive. I was myself thinking about perhaps just making a new spigot page for this. Let me know what you think, and keep up the good work :wink:

**Comment by KevinDaGame** [comment]
> Hi, just saw this, I also opened a PR for this, but unfortunately the original author seems really inactive. I was myself thinking about perhaps just making a new spigot page for this. Let me know what you think, and keep up the good work 😉

I Included most of your changes in this yeah. I might but right now I don't feel like maintaining it on my own. I just have too much to do right now.

**Comment by Lennart99** [comment]
> I Included most of your changes in this yeah. I might but right now I don't feel like maintaining it on my own. I just have too much to do right now.

I had the same struggle, I just do not enough time to fully commit to something like this. I would however be open to collaborate on something like this, if you would be interested.

**Comment by KevinDaGame** [comment]
> > I Included most of your changes in this yeah. I might but right now I don't feel like maintaining it on my own. I just have too much to do right now.
> 
> I had the same struggle, I just do not enough time to fully commit to something like this. I would however be open to collaborate on something like this, if you would be interested.

Sounds fun, feel free to join my discord to talk more https://discord.gg/YDjykYsAFF

**Comment by KevinDaGame** [comment]
This pull request will no longer supply the latest jars. For the updated source, please see https://github.com/KevinDaGame/VoxelSniper. If you have any questions. Please join https://discord.gg/YDjykYsAFF

**Pull request closed without merging**
